### PR TITLE
Fix numbering and broken links

### PR DESCRIPTION
**Pull request by bast**

### CODE REVIEW

**Review by johanhellsvik — COMMENTED** [review]
The link https://raw.githubusercontent.com/coderefinery/jupyter/main/example/darts.svg
is not working

**Comment by bast** [comment]
> The link https://raw.githubusercontent.com/coderefinery/jupyter/main/example/darts.svg
> is not working

I will (hopefully) work after this PR is in. The file move is part of this PR. But thanks for pointing it out.

**Comment by bast** [comment]
... I should have written this in the PR description. Sorry.

**Comment by bast** [comment]
Merging. Thanks for careful review. I should write better descriptions.

**Pull request merged**
