### PR TITLE
implement jekyll layout for jupyter lesson

### PR DESCRIPTION
**Pull request by wikfeldt**
This was suggested in #26 . I think teaching this way will be more structured, and more easily timed correctly.
The first exposure to a notebook workflow is now the compute-pi idea from @rkdarst , while the word-count exercise is instead an exercise. 

Left to do:
- adjust timing for each episode
- include final exercise on creating a notebook repository on GitHub and connecting it to mybinder, and add a mybinder batch to the README

### CODE REVIEW

**Comment by wikfeldt** [comment]
the resulting lesson can be viewed at https://wikfeldt.github.io/jupyter/

**Comment by bast** [comment]
Looks very good! The one question I was asking myself is whether the exercises should not be separate episodes. Also the timing is too optimistic in some episodes. One suggestion I will make on our group chat is to show episode lengths instead of episode start times in the overview.

**Comment by wikfeldt** [comment]
thanks for checking. So the episode timings are currently meaningless, i will update them.
I'll think about moving the exercises into the other episodes, it's not straightforward. my thinking around that is that people will have different usecases for jupyter (which is different from e.g. git that everyone uses in similar ways), so it's good to have a smorgasbord of exercises that participants can choose between

**Comment by bast** [comment]
Good point about smorgasbord - I like that :-) So let's only adjust timings and then we merge. There are minor things I would like to change but I can do that as follow-up PRs.

**Comment by wikfeldt** [comment]
huh, i accidentally merged the PR by pushing to this repo instead of my fork. Oh well, timing has been updated, exercises have solutions and instructor guide is updated (but should be expanded/polished).

**Pull request merged**
