### PR TITLE
Thor/jupyterlab

### PR DESCRIPTION
**Pull request by wikfeldt**
new step-by-step exercises, all clumped together so learners depending on interest can choose which ones to work on. Also tried to have a logical separation between 1st introductory/overview notebook and 2nd use-case/hands-on notebook

### CODE REVIEW

**Comment by bast** [comment]
It's a bit hard to see what happened from the diff (usual Jupyter problem). Can you post a link to where the WIP project is rendered?

**Comment by wikfeldt** [comment]
yes it's the usual annoying ipynb problem. Only thing i can think of now is to use nbviewer for each branch separately and manually compare. Diffs now look quite nice inside Jupyterlab thanks to nbdime, but i'm not aware of it being possible on github. Anyways here are the notebooks:
`master`:
https://nbviewer.jupyter.org/github/coderefinery/jupyterlab/blob/master/basics_of_jupyter.ipynb
https://nbviewer.jupyter.org/github/coderefinery/jupyterlab/blob/master/data_analysis_visualization.ipynb

`thor/jupyterlab`
https://nbviewer.jupyter.org/github/coderefinery/jupyterlab/blob/thor%2Fjupyterlab/basics_of_jupyter.ipynb
https://nbviewer.jupyter.org/github/coderefinery/jupyterlab/blob/thor%2Fjupyterlab/data_analysis_visualization.ipynb

**Comment by bast** [comment]
Looks very good.

Personally I always felt that we allocated quite a lot of time for magics and we spent only 5 minutes on motivating.

I would suggest that we spend a bit more time on discussing when and why Jupyter:
- pros/cons
- examples/ use cases when to use and when not to use
- "what you probably do today" vs. how this could look when using Jupyter

**Comment by wikfeldt** [comment]
I agree that we shouldn't spend too much time on magics, and rather try to focus on use cases. The notebooks now have sections "when not to jupyter" and "jupyter use cases", and the exercises (now in separate notebook) are meant to cover some possible use cases.

""what you probably do today" vs. how this could look when using Jupyter" is a good idea for a discussion point and i'll add it, but i'm not sure how to stress the use cases and pros/cons better. Any ideas welcome

**Comment by bast** [comment]
We could leave that point up for discussion and simply list the typical 4-6 things people do in daily research and then we could ask the participants to tell how they solve it today and we could discuss how this could look in the Jupyter world.

**Comment by wikfeldt** [comment]
i think we're ready to merge. The found notebooks are rendered at:
- [basics](https://nbviewer.jupyter.org/github/coderefinery/jupyterlab/blob/thor%2Fjupyterlab/basics_of_jupyter.ipynb)
- [use cases](https://nbviewer.jupyter.org/github/coderefinery/jupyterlab/blob/thor%2Fjupyterlab/jupyter_usecases.ipynb)
- [exercises](https://nbviewer.jupyter.org/github/coderefinery/jupyterlab/blob/thor%2Fjupyterlab/exercises.ipynb)
- [solutions](https://nbviewer.jupyter.org/github/coderefinery/jupyterlab/blob/thor%2Fjupyterlab/solutions.ipynb)

**Comment by bast** [comment]
Thanks! Very minor comment:

The code examples often lack spaces, e.g.:
```python
result = somefunction(x,y,z=2.0)
```
Instead of (better, easier to read, following PEP8):
```python
result = somefunction(x, y, z=2.0)
```
For those who see Python for the first time we should give a good example.

**Pull request merged**
